name: Merge
on:
  pull_request:
    branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/docker
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          cd ..
          touch .env
          echo "POSTGRES_DB=test_db" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "DJANGO_SECRET_KEY=test-secret-key" >> .env
          echo "DEBUG=False" >> .env
      
      - name: Build lint image
        run: docker compose build lint
        
      - name: Run Linting
        run: docker compose run --rm lint
  